name: Daily Commit Bot

on:
  schedule:
    - cron: '15 5 * * *'   # Runs daily at 05:15 UTC (you can adjust)
  workflow_dispatch:        # Allows manual run

permissions:
  contents: write           # <— IMPORTANT! allows push

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a daily commit (23f2000689@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date)" > last_run.txt
          git config user.name "GitHub Action Bot"
          git config user.email "23f2000689@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated daily commit - $(date)" || echo "No changes to commit"
          git push

